# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\"\\\n\x14\x43reateMessageRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"[\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\x05\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t\"F\n\x13ListMessagesRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"1\n\x0bMessageList\x12\"\n\x08messages\x18\x01 \x03(\x0b\x32\x10.message.Message2\x96\x01\n\x0eMessageService\x12@\n\rCreateMessage\x12\x1d.message.CreateMessageRequest\x1a\x10.message.Message\x12\x42\n\x0cListMessages\x12\x1c.message.ListMessagesRequest\x1a\x14.message.MessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEMESSAGEREQUEST']._serialized_start=26
  _globals['_CREATEMESSAGEREQUEST']._serialized_end=118
  _globals['_MESSAGE']._serialized_start=120
  _globals['_MESSAGE']._serialized_end=211
  _globals['_LISTMESSAGESREQUEST']._serialized_start=213
  _globals['_LISTMESSAGESREQUEST']._serialized_end=283
  _globals['_MESSAGELIST']._serialized_start=285
  _globals['_MESSAGELIST']._serialized_end=334
  _globals['_MESSAGESERVICE']._serialized_start=337
  _globals['_MESSAGESERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
