# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = "1.75.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in message_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMessage = channel.unary_unary(
            "/message.MessageService/CreateMessage",
            request_serializer=message__pb2.CreateMessageRequest.SerializeToString,
            response_deserializer=message__pb2.Message.FromString,
            _registered_method=True,
        )
        self.ListMessages = channel.unary_unary(
            "/message.MessageService/ListMessages",
            request_serializer=message__pb2.ListMessagesRequest.SerializeToString,
            response_deserializer=message__pb2.MessageList.FromString,
            _registered_method=True,
        )


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateMessage": grpc.unary_unary_rpc_method_handler(
            servicer.CreateMessage,
            request_deserializer=message__pb2.CreateMessageRequest.FromString,
            response_serializer=message__pb2.Message.SerializeToString,
        ),
        "ListMessages": grpc.unary_unary_rpc_method_handler(
            servicer.ListMessages,
            request_deserializer=message__pb2.ListMessagesRequest.FromString,
            response_serializer=message__pb2.MessageList.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "message.MessageService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("message.MessageService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/message.MessageService/CreateMessage",
            message__pb2.CreateMessageRequest.SerializeToString,
            message__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/message.MessageService/ListMessages",
            message__pb2.ListMessagesRequest.SerializeToString,
            message__pb2.MessageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
