# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'db_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x62_service.proto\x12\ndb_service\"\x07\n\x05\x45mpty\"\x17\n\tSessionId\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x14\x43reateSessionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x14UpdateSessionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bis_favorite\x18\x03 \x01(\x08\"8\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bis_favorite\x18\x03 \x01(\x08\"4\n\x0bSessionList\x12%\n\x08sessions\x18\x01 \x03(\x0b\x32\x13.db_service.Session\"\\\n\x14\x43reateMessageRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\"[\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\x05\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t\"F\n\x13ListMessagesRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x0c\n\x04skip\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\"4\n\x0bMessageList\x12%\n\x08messages\x18\x01 \x03(\x0b\x32\x13.db_service.Message2\xa4\x03\n\tDBService\x12\x46\n\rCreateSession\x12 .db_service.CreateSessionRequest\x1a\x13.db_service.Session\x12:\n\x0cListSessions\x12\x11.db_service.Empty\x1a\x17.db_service.SessionList\x12\x46\n\rUpdateSession\x12 .db_service.UpdateSessionRequest\x1a\x13.db_service.Session\x12\x39\n\rDeleteSession\x12\x15.db_service.SessionId\x1a\x11.db_service.Empty\x12\x46\n\rCreateMessage\x12 .db_service.CreateMessageRequest\x1a\x13.db_service.Message\x12H\n\x0cListMessages\x12\x1f.db_service.ListMessagesRequest\x1a\x17.db_service.MessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_SESSIONID']._serialized_start=41
  _globals['_SESSIONID']._serialized_end=64
  _globals['_CREATESESSIONREQUEST']._serialized_start=66
  _globals['_CREATESESSIONREQUEST']._serialized_end=102
  _globals['_UPDATESESSIONREQUEST']._serialized_start=104
  _globals['_UPDATESESSIONREQUEST']._serialized_end=173
  _globals['_SESSION']._serialized_start=175
  _globals['_SESSION']._serialized_end=231
  _globals['_SESSIONLIST']._serialized_start=233
  _globals['_SESSIONLIST']._serialized_end=285
  _globals['_CREATEMESSAGEREQUEST']._serialized_start=287
  _globals['_CREATEMESSAGEREQUEST']._serialized_end=379
  _globals['_MESSAGE']._serialized_start=381
  _globals['_MESSAGE']._serialized_end=472
  _globals['_LISTMESSAGESREQUEST']._serialized_start=474
  _globals['_LISTMESSAGESREQUEST']._serialized_end=544
  _globals['_MESSAGELIST']._serialized_start=546
  _globals['_MESSAGELIST']._serialized_end=598
  _globals['_DBSERVICE']._serialized_start=601
  _globals['_DBSERVICE']._serialized_end=1021
# @@protoc_insertion_point(module_scope)
