# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x07session\"\x07\n\x05\x45mpty\"\x17\n\tSessionId\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x14\x43reateSessionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x14UpdateSessionRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bis_favorite\x18\x03 \x01(\x08\"8\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bis_favorite\x18\x03 \x01(\x08\"1\n\x0bSessionList\x12\"\n\x08sessions\x18\x01 \x03(\x0b\x32\x10.session.Session2\xff\x01\n\x0eSessionService\x12@\n\rCreateSession\x12\x1d.session.CreateSessionRequest\x1a\x10.session.Session\x12\x34\n\x0cListSessions\x12\x0e.session.Empty\x1a\x14.session.SessionList\x12@\n\rUpdateSession\x12\x1d.session.UpdateSessionRequest\x1a\x10.session.Session\x12\x33\n\rDeleteSession\x12\x12.session.SessionId\x1a\x0e.session.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_SESSIONID']._serialized_start=35
  _globals['_SESSIONID']._serialized_end=58
  _globals['_CREATESESSIONREQUEST']._serialized_start=60
  _globals['_CREATESESSIONREQUEST']._serialized_end=96
  _globals['_UPDATESESSIONREQUEST']._serialized_start=98
  _globals['_UPDATESESSIONREQUEST']._serialized_end=167
  _globals['_SESSION']._serialized_start=169
  _globals['_SESSION']._serialized_end=225
  _globals['_SESSIONLIST']._serialized_start=227
  _globals['_SESSIONLIST']._serialized_end=276
  _globals['_SESSIONSERVICE']._serialized_start=279
  _globals['_SESSIONSERVICE']._serialized_end=534
# @@protoc_insertion_point(module_scope)
